name: project1
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1   # ✅ added for text styling
  shared_preferences: ^2.2.3 
  intl: ^0.19.0
  audioplayers: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # ✅ Added your image asset here
  assets:
    - assets/girl.png
    - assets/rain_sound.mp3
